version: '3.5'
services:
    nginx:
      image: nginx:1.16.0
      environment:
        - NGINX_SERVER_NAME=localhost
        - NGINX_PORT=8085
        - NGINX_ROOT=/var/www/horizon-test/public
      working_dir: ${APP_DIR}
      command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
      volumes:
          - ".:${APP_DIR}"
          - ./docker/nginx/laravel5.template:/etc/nginx/conf.d/template
      networks:
          local:
              aliases:
                - horizon-test
      depends_on:
          - php
          - code
      ports:
          - "8085:8085"
      expose:
          - "8085"
    postgres:
      env_file:
        - .env
      image: postgres:11.1
      restart: always
      ports:
        - "5431"
      environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_HOST_AUTH_METHOD: trust
      volumes:
        - "dbdata:/var/lib/postgresql/data"
      networks:
        - local
    php:
      env_file:
        - .env
      working_dir: /var/www/app/
      image: php:7.4
      restart: on-failure
      environment:
        PHP_ENABLED_EXTENSIONS: "amqp apcu opcache xdebug mcrypt sodium redis zip pdo_pgsql gd gmp"
        XDEBUG_CONFIG: "remote_host=172.17.0.1 client_port=9001"
        PHP_ALLOW_URL_FOPEN: "On"
        PHP_MAX_EXECUTION_TIME: 60
        PHP_MAX_INPUT_TIME: 60
        PHP_MEMORY_LIMIT: "256M"
        PHP_POST_MAX_SIZE: "120M"
        PHP_UPLOAD_MAX_FILESIZE: "100M"
        PHP_SHORT_OPEN_TAG: "On"
        PHP_DISPLAY_ERRORS: "On"
        PHP_DISPLAY_STARTUP_ERRORS: "On"
      volumes:
          - ".:${APP_DIR}"
      networks:
          - local


    adminer:
      image: adminer:4.7.5
      restart: always
      environment:
          ADMINER_DESIGN: nette
      depends_on:
        - postgres
      ports:
          - 8080:8080
      networks:
          local:
              aliases:
                - adminer.horizon-test
    redis:
      image: redis:5.0.5
      sysctls:
          net.core.somaxconn: 1024
      volumes:
          - "redisdata:/data"
      networks:
          - local
    exim:
      build:
          context: docker/exim
          dockerfile: Dockerfile
      environment:
          PRIMARY_HOST: mail.local
          ALLOWED_HOSTS: php ; 10.0.0.0/8 ; 172.16.0.0/12 ; 192.168.0.0/16
      volumes:
          - "eximdata:/var/spool/exim4"
      networks:
          - local
    code:
      build:
          context: .
          dockerfile: Dockerfile
          args:
              - SOURCE_FOLDER=/source
      volumes:
          - "appdata:${APP_DIR}"
      command: /bin/sh -c "rm -rf ${APP_DIR}/*; cp -rp * ${APP_DIR}; cp -rp . ${APP_DIR}; chown -R www-data:www-data ${APP_DIR}"
      networks:
          - local

networks:
    local:

volumes:
    appdata:
        driver: local
    dbdata:
        driver: local
    redisdata:
        driver: local
    eximdata:
        driver: local
